# Generated by Django 4.2.2 on 2023-07-09 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='Fecha de creación')),
                ('status', models.CharField(choices=[('On hold', 'On hold'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded'), ('Failed', 'Failed')], max_length=12, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Subtotal')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Descuento por puntos')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total')),
                ('payment_method', models.CharField(blank=True, choices=[('Paypal', 'Paypal'), ('Stripe', 'Stripe')], max_length=20, null=True, verbose_name='Metodo de Pago')),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Transacción')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre del destinatario')),
                ('city', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('address_1', models.CharField(max_length=60, verbose_name='Dirección de calle')),
                ('address_2', models.CharField(blank=True, max_length=60, null=True, verbose_name='Numero de edificio, casa etc.')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Codigo Postal')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='ShippingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Empresa de envio')),
                ('tracking_link', models.URLField(blank=True, verbose_name='Enlace para el tracking')),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking', models.CharField(max_length=50, verbose_name='Tracking')),
                ('shipping_date', models.DateField(verbose_name='Fecha de envio')),
                ('tracking_link', models.URLField(blank=True, verbose_name='Enlace del tracking')),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_tracking', to='order.order', verbose_name='ID Orden')),
                ('shipping_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.shippingcompany', verbose_name='Empresa de envio')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Subtotal')),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order', verbose_name='ID del pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Producto')),
            ],
        ),
    ]
