# Generated by Django 4.1.7 on 2023-04-02 06:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0002_remove_order_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Subtotal')),
                ('id_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='ID del carrito')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='product.product', verbose_name='Producto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
