# Generated by Django 4.2.3 on 2023-07-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default='example', max_length=50, verbose_name='Producto'),
            preserve_default=False,
        ),
    ]
