# Generated by Django 4.1.7 on 2023-04-05 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0001_initial'),
        ('order', '0003_orderitem_delete_orderproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='')),
                ('tracking_link', models.URLField(blank=True, verbose_name='Enlace para el tracking')),
            ],
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='id_cart',
            new_name='id_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='modified',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Paypal', 'Paypal'), ('Stripe', 'Stripe')], max_length=20, verbose_name='Metodo de Pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('En espera', 'En espera'), ('Enviado', 'Enviada'), ('Cancelado', 'Cancelado'), ('Reembolsado', 'Reembolsado')], default=1, max_length=12, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID Transacción'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='product.product', verbose_name='Producto'),
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking', models.CharField(max_length=50, verbose_name='Tracking')),
                ('tracking_link', models.URLField(blank=True, verbose_name='Enlace del tracking')),
                ('shipping_date', models.DateField(auto_now_add=True)),
                ('shipping_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.shippingcompany', verbose_name='Empresa de envio')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre del destinatario')),
                ('city', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('address_1', models.CharField(max_length=60, verbose_name='Dirección de calle')),
                ('address_2', models.CharField(blank=True, max_length=60, null=True, verbose_name='Numero de edificio, casa etc.')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Codigo Postal')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.country')),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.state')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
