# Generated by Django 4.1.7 on 2023-04-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_shippingcompany_rename_id_cart_orderitem_id_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Paypal', 'Paypal'), ('Stripe', 'Stripe')], max_length=20, null=True, verbose_name='Metodo de Pago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('En espera', 'En espera'), ('Enviado', 'Enviado'), ('Cancelado', 'Cancelado'), ('Reembolsado', 'Reembolsado')], max_length=12, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Transacción'),
        ),
    ]
