# Generated by Django 4.1.7 on 2023-04-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_payment_method_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Total'),
            preserve_default=False,
        ),
    ]
