# Generated by Django 4.1.7 on 2023-04-06 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_discount_alter_order_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='id_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='ID Orden'),
            preserve_default=False,
        ),
    ]
