# Generated by Django 4.1.7 on 2023-04-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_tracking_id_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Precio unitario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Empresa de envio'),
        ),
    ]
