# Generated by Django 4.1.7 on 2023-04-11 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0011_alter_order_created_alter_tracking_id_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='id_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order', verbose_name='ID del carrito'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Producto'),
        ),
    ]
