# Generated by Django 4.1.7 on 2023-04-15 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0017_alter_cart_subtotal_alter_cart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='id_cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='order.order', verbose_name='ID del pedido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Producto'),
            preserve_default=False,
        ),
    ]
