# Generated by Django 4.1.7 on 2023-02-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_address_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='address_1',
            field=models.CharField(default=1, max_length=60, verbose_name='Dirección de calle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='address_2',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Numero de edificio, casa etc.'),
        ),
    ]
