# Generated by Django 4.1.6 on 2023-02-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_address_user_city_user_country_user_state_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero de Telefono'),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Codigo Postal'),
        ),
    ]
