# Generated by Django 4.1.7 on 2023-05-22 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_of_earning_points', models.IntegerField(verbose_name='Tasa de puntos por dolar')),
                ('redemption_rate', models.IntegerField(verbose_name='Tasa de Canjeo por dolar')),
            ],
        ),
        migrations.CreateModel(
            name='UserPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='Puntos')),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_points', to=settings.AUTH_USER_MODEL, verbose_name='Puntos del usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PointsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='Puntos')),
                ('event', models.CharField(blank=True, max_length=40, verbose_name='Evento')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('user_points', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_history', to='points.userpoint', verbose_name='Historial de puntos')),
            ],
        ),
    ]
