# Generated by Django 4.2.3 on 2023-07-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='Puntos')),
                ('event', models.CharField(max_length=40, verbose_name='Evento')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='PointsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning_points_rate', models.IntegerField(default=1, verbose_name='Tasa de puntos por dolar')),
                ('redemption_rate', models.IntegerField(default=35, verbose_name='Tasa de Canjeo por dolar')),
            ],
        ),
        migrations.CreateModel(
            name='UserPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Puntos')),
            ],
        ),
    ]
