# Generated by Django 4.2.3 on 2023-07-12 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('points', '0001_initial'),
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoint',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_points', to=settings.AUTH_USER_MODEL, verbose_name='Puntos del usuario'),
        ),
        migrations.AddField(
            model_name='pointshistory',
            name='id_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Id de la orden'),
        ),
        migrations.AddField(
            model_name='pointshistory',
            name='user_points',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_history', to='points.userpoint', verbose_name='Puntos del Usuario'),
        ),
    ]
