# Generated by Django 4.1.7 on 2023-05-22 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_alter_order_status'),
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointshistory',
            name='id_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Id de la orden'),
        ),
        migrations.AlterField(
            model_name='pointshistory',
            name='event',
            field=models.CharField(max_length=40, verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='pointssetting',
            name='rate_of_earning_points',
            field=models.IntegerField(default=1, verbose_name='Tasa de puntos por dolar'),
        ),
        migrations.AlterField(
            model_name='pointssetting',
            name='redemption_rate',
            field=models.IntegerField(default=35, verbose_name='Tasa de Canjeo por dolar'),
        ),
        migrations.AlterField(
            model_name='userpoint',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Puntos'),
        ),
    ]
